version: '2'
services:
  nextcloud:
    build: .
    image: asannou/nextcloud:strict
    container_name: nextcloud
    volumes:
      - ./config.php:/var/www/nextcloud/config/config.php
      - ./data:/var/www/nextcloud/data
  proxy:
    build: proxy
    image: asannou/nextcloud-sharing-only-proxy
    container_name: nextcloud-proxy
    ports:
      - '80:80'
      - '8000:8000'
    cap_add:
      - NET_ADMIN
    depends_on:
      - nextcloud
