version: '2'
services:
  nextcloud:
    build: .
    image: asannou/nextcloud:11-strict
    container_name: nextcloud
    volumes:
      - ./volume:/volume
  proxy:
    build: proxy
    image: asannou/nextcloud-sharing-only-proxy:strict
    container_name: nextcloud-proxy
    ports:
      - '80:80'
      - '8000:8000'
    cap_add:
      - NET_ADMIN
    depends_on:
      - nextcloud
