version: '2'
services:
  nextcloud:
    build:
      context: .
      args:
        version: "${DOCKER_NEXTCLOUD_IMAGE_VERSION}"
    image: "asannou/nextcloud:${DOCKER_NEXTCLOUD_IMAGE_VERSION}${DOCKER_NEXTCLOUD_IMAGE_BRANCH}"
    container_name: nextcloud
    volumes:
      - ./volume:/volume
      - ./volume/nextcloud:/var/www/html
    depends_on:
      - antivirus
  proxy:
    build: proxy
    image: "asannou/nextcloud-sharing-only-proxy:${DOCKER_NEXTCLOUD_IMAGE_VERSION}${DOCKER_NEXTCLOUD_IMAGE_BRANCH}"
    container_name: nextcloud-proxy
    ports:
      - '80:80'
      - '8000:8000'
    depends_on:
      - nextcloud
  antivirus:
    image: clamav/clamav:stable_base
    container_name: clamav
    volumes:
      - ./volume/clamav/virus_db/:/var/lib/clamav/
