#!/bin/sh
#
#       /etc/rc.d/init.d/docker-nextcloud
#
#       Nextcloud docker container
#
# chkconfig:   2345 99 01
# description: Start and stop asannou/nextcloud* docker containers

### BEGIN INIT INFO
# Provides:       docker-nextcloud
# Required-Start: docker
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Short-Description: Nextcloud docker container
# Description: Start and stop asannou/nextcloud* docker containers
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

prog="docker"
exec="/usr/bin/$prog"
name="nextcloud"
proxyname="nextcloud-proxy"
image="asannou/nextcloud:strict"
proxyimage="asannou/nextcloud-sharing-only-proxy:strict"
valume="/volume"
port="80"
internalport="8000"

start() {
    $exec start $name $proxyname
}

stop() {
    $exec stop $proxyname $name
}

restart() {
    stop
    start
}

run() {
    $exec run -d --name $name -v $valume:/volume $image > /dev/null
    $exec run -d --cap-add=NET_ADMIN --name $proxyname -p ${internalport}:8000 -p ${port}:80 --link $name $proxyimage > /dev/null
}

rm() {
    $exec rm -f $proxyname $name
}

case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    run)
        $1
        ;;
    rm)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|run|rm}"
        exit 2
esac

exit $?
