name: Publish Docker image

on:
  push:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: nextcloud
        uses: docker/metadata-action@v5
        with:
          images: asannou/nextcloud
          tags: |
            type=raw,value={{branch}}

      - name: Extract metadata (tags, labels) for Docker
        id: proxy
        uses: docker/metadata-action@v5
        with:
          images: asannou/nextcloud-sharing-only-proxy
          tags: |
            type=raw,value={{branch}}

      - id: env
        run: cat .env >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: version=${{ steps.env.outputs.DOCKER_NEXTCLOUD_IMAGE_VERSION }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.nextcloud.outputs.tags }}
          labels: ${{ steps.nextcloud.outputs.labels }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: proxy
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.proxy.outputs.tags }}
          labels: ${{ steps.proxy.outputs.labels }}
