name: Publish Docker image

on:
  push:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: nextcloud
        uses: docker/metadata-action@v3
        with:
          images: asannou/nextcloud
          tags: |
            type=raw,value={{branch}}

      - name: Extract metadata (tags, labels) for Docker
        id: proxy
        uses: docker/metadata-action@v3
        with:
          images: asannou/nextcloud-sharing-only-proxy
          tags: |
            type=raw,value={{branch}}

      - id: nextcloud-version
        run: |
          REF_NAME="${{ github.ref_name }}"
          echo "version=${REF_NAME%%-*}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: version=${{ steps.nextcloud-version.outputs.version }}
          push: true
          tags: ${{ steps.nextcloud.outputs.tags }}
          labels: ${{ steps.nextcloud.outputs.labels }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: proxy
          push: true
          tags: ${{ steps.proxy.outputs.tags }}
          labels: ${{ steps.proxy.outputs.labels }}
